# 100 numpy exerices
## numpy 1-10
### Import the numpy package under the name

In [1]:
import numpy as np

### Print the numbpy version and the configuration

In [2]:
print (np.__version__)

1.14.0


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/P

### Create a null vector of size 10

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### How to get the documentation of the numpy add function from the command line?

関数のインフォメーションを得る方法 .


In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### Create a  null vector  of  size 10 but the fifth value which is 1

In [8]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [9]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector

In [10]:
z = np.arange(10)
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Create a 3x3 matrix with values rangin from 0 to 8

In [13]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of  non-zero elements from ....

非ゼロの要素位置を取得する. 


In [14]:
nz = np.nonzero([1,2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### Create a 3x3 idenitty matrix

In [15]:
Z = np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## numpy 11-20

### Create a  3x3x3 array with random values

In [18]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.91122417 0.56828947 0.23633536]
  [0.10220123 0.28599255 0.54029441]
  [0.02286248 0.93490127 0.16171255]]

 [[0.67595612 0.3147668  0.11979286]
  [0.25812327 0.19486783 0.03558846]
  [0.29129678 0.20383647 0.54605535]]

 [[0.01942731 0.33180026 0.053851  ]
  [0.21845907 0.1566309  0.4072349 ]
  [0.02052922 0.03294294 0.6911378 ]]]


### Create 10x10 array with uniform random values and find the minimum and maximum values

In [19]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00015150843942624004 0.9956928470144872


### Create a random vector of size 30 and find the mean

In [20]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.40525162533001396


### Create a  2d array with 1 on the border and 0 inside


In [22]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### What is the result of the following expression

Rだと`nan`の演算はすべて`nan`であるけど、Pythonでは違うようだ. 
不等式の演算はTrue/Falseが帰り値になっている. 



In [24]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
.3 == 3 * .1)

nan False False nan False


### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

引数のkは対角行列とする部分をずらすイメージでいればよい. 
k > 0 でカラム方向にずれていく. 時空間データでは必要になる場面が生じると考えられる。



In [2]:
Z = np.diag(1 + np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [3]:
np.diag(1 + np.arange(4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [4]:
np.diag(1 + np.arange(4), k = 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [6]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

### Create a 8x8 matrix and fill it with a checkerboard pattern 

しましまを作る. 

In [8]:
Z = np.zeros((8,8), dtype = int)
Z[1::2,::2] = 1 #基数行のしましま
Z[::2,1::2] = 1 #偶数行のしましま
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Consider a (6,7,8) shape array, what is the index(x,y,z) of the 100th element?

In [10]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [13]:
print(np.unravel_index(3, (2,2)))

(1, 1)


### Create a checkeboard 8x8 matrix using the tile function

これはときどき便利になるのでは・・・！？


In [15]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5x5 random matrix

In [17]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[0.92195759 0.90902994 0.59094475 0.12961208 0.9172407 ]
 [0.10333932 1.         0.08201881 0.29765987 0.53398901]
 [0.67572976 0.00371644 0.71072218 0.27422933 0.73951862]
 [0.13472703 0.28415139 0.         0.55883039 0.10891194]
 [0.82819286 0.75149406 0.16878198 0.60756313 0.57784852]]


## numpy 21-30

### Create a custom dtype that describes a color as four unisgned bytes

In [19]:
color = np.dtype([
    ("r", np.ubyte, 1), 
    ("g", np.ubyte, 1), 
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### Multiply a 5x3 matrix by a 3x2 matrix

In [21]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### Given a 1D array, negate all elements which are between 3 and 8, in place

In [23]:
# Author: Evgeni Burovki
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### What is the output of the following script ?

これは恐い。。。pythonにライブラリーを読み込むときには、必ずmoduleとして読み込むということを意識したい。。。

In [25]:
# Author: Jake VanderPlas

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


### Consider an integer vector Z,, which of these expressions are legal?

In [43]:
Z = np.arange(5, dtype = np.int)
print(
    Z ** Z, 
    2 << Z, # 2をZビット左にずらす  001 -> 100, 
    Z >> 2, # Zを2ビット右にずらす　100 -> 001
    2 << Z >> 2, 
    1j * Z, 
    Z / 1/ 1, 
    # Z < Z > Z
)

[  1   1   4  27 256] [ 2  4  8 16 32] [0 0 0 0 1] [0 1 2 4 8] [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j] [0. 1. 2. 3. 4.]


### What are the result of the following expressions?

In [46]:
print(
    np.array(0), 
    np.array(0) // np.array(0), 
    np.array(0) // np.array(.0),
    np.array(0) / np.array(0.),
    np.array(0) / np.array(0)
)

0 0 nan nan nan


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in floor_divide
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


### How to round away from zero a float array


In [49]:
# Author: Charles R Harris

Z = np.random.uniform(-10, 10, 10)
print(
    np.trunc(Z + np.copysign(.5, Z))
)

[-2. -1. -7.  4. -7.  4. -7. -5.  9. -0.]


In [55]:
# 0.5に、Zの符号をコピーさせる
np.copysign(.5, Z)

array([-0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5])

In [56]:
Z

array([-1.65708739, -1.48084382, -7.04114379,  3.86602668, -6.94377156,
        4.496215  , -6.80105232, -5.28647511,  8.97518993, -0.28001812])

### Extract the integer part of a random arrary using 5 diffrent methods

In [60]:
Z = np.random.uniform(-10, 10, 10)

print (Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 6.74706849 -9.26265319  8.20958221 -4.46451684 -4.45367709  3.73600485
 -4.81089396 -2.79760124 -7.87712466  0.29938869]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[ 6 -9  8 -4 -4  3 -4 -2 -7  0]
[ 6. -9.  8. -4. -4.  3. -4. -2. -7.  0.]


In [61]:
Z%1

array([0.74706849, 0.73734681, 0.20958221, 0.53548316, 0.54632291,
       0.73600485, 0.18910604, 0.20239876, 0.12287534, 0.29938869])

### Create a 5x5 matrix with row values ranging from 0 to 4

In [63]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Consider a generator function that generates 10 integers and use it to build an array

In [66]:
def generate():
    for x in arange(10):
        yield x

Z = np.fromiter(generate(), dtype = float, count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## numpy 31-40

### Create a vector of size 10 with values ranging from 0 to 1, both excluded

`endpoint=True`を使うことで両端を含んだ値を得ることができ、そこから両端を除く処理をすればタイトルの数列を得ることが可能. 

In [5]:
import numpy as np
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [6]:
np.linspace(0, 1, 12, endpoint=True)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### Create a random vector of size 10 and sort it

In [8]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.28015316 0.35805699 0.45053388 0.52056747 0.53223267 0.54585569
 0.75495564 0.77145258 0.81702613 0.89325511]


### How to sum a small array faster than np.sum?

In [10]:
Z = np.arange(10)
np.add.reduce(Z)

45

### Consider two random array A and B, check if they are equal

In [13]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal = np.allclose(A, B)
print(A, "\n", B, "\n", equal)

[1 1 1 1 1] 
 [0 0 1 0 0] 
 False


### Make an array immutable

In [15]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

### Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [18]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.67629197 1.25714105 0.5293896  0.7978414  0.272049   0.64296495
 0.81863128 0.39357904 0.88671327 0.67294112]
[0.25624045 0.74088551 0.38294927 1.45055484 0.70569002 1.15432196
 0.3786069  0.99945527 0.33311962 0.11869638]


### Craeate random vector of size 10 and replace the maximum value by 0

In [20]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.61986427 0.841745   0.88700695 0.         0.70597891 0.44162934
 0.08942469 0.80091992 0.36327868 0.04875955]


### Create a structured array with x and y coordiantes converting the [0,1]x[0,1] area


構造化とはつまり、列名と列の型を指定できるという意味のようだ。それにしてもこの`meshgrid`は便利な気がする. 

In [23]:
Z = np.zeros((10,10), [('x', float), ('y', float)])

In [26]:
Z['x'], Z['y'] = np.meshgrid(
        np.linspace(0, 1, 10), 
        np.linspace(0, 1, 10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

### Given two arrays , X and Y, construct the Cauchy matrix C

In [29]:
X = np.arange(8)
Y = X + .5
C = 1. / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [33]:
# X - Yを外積で組み合わせて演算をしてくれる
np.subtract.outer(X,Y)

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [34]:
np.add.outer(X, Y)

array([[ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5],
       [ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5],
       [ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5],
       [ 3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5],
       [ 4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5],
       [ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5],
       [ 6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5],
       [ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5]])

### print minimum and maximum representable value for each numpy  scalar type

In [36]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [38]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## numpy 41-50

### How to print all the values of an array

In [40]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25, 25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

### How to find the closest value in an array

In [44]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

38


### Create a structured array representing a position(x,y) and color(r,g,b)

In [46]:
Z = np.zeros(10, [
        ('position', [('x', float, 1), ('y', float, 1)]), 
        ('color', [('r', float, 1), ('g', float, 1), 
                  ('b', float, 1)])])

In [48]:
Z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [49]:
Z[0]

((0., 0.), (0., 0., 0.))

### Consider a random vector with shape(1000,2) representing coordinates, find point by point distances

In [55]:
Z = np.random.random((5,2))
X, Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt((X - X.T) ** 2 + (Y-Y.T)**2)
print(D)

[[0.         0.47753076 0.26559542 0.69092237 0.26628868]
 [0.47753076 0.         0.37385629 0.32012017 0.53624286]
 [0.26559542 0.37385629 0.         0.47082045 0.16521815]
 [0.69092237 0.32012017 0.47082045 0.         0.61955298]
 [0.26628868 0.53624286 0.16521815 0.61955298 0.        ]]


In [53]:
# Much faster with scipy
import scipy.spatial

In [57]:
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.47753076 0.26559542 0.69092237 0.26628868]
 [0.47753076 0.         0.37385629 0.32012017 0.53624286]
 [0.26559542 0.37385629 0.         0.47082045 0.16521815]
 [0.69092237 0.32012017 0.47082045 0.         0.61955298]
 [0.26628868 0.53624286 0.16521815 0.61955298 0.        ]]


In [59]:
print(X - X.T)

[[ 0.          0.06365868 -0.18308825 -0.19410546 -0.26205754]
 [-0.06365868  0.         -0.24674693 -0.25776414 -0.32571623]
 [ 0.18308825  0.24674693  0.         -0.01101721 -0.07896929]
 [ 0.19410546  0.25776414  0.01101721  0.         -0.06795209]
 [ 0.26205754  0.32571623  0.07896929  0.06795209  0.        ]]


### How to convert a float array into an integer inplace

In [62]:
Z = np.arange(10, dtype = np.int32)
Z = Z.astype(np.float32, copy = False)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

### How to read the following file

In [64]:
# File content:
# -------------
#1,2,3,4,5
#6,,,7,8
#,,9,10,11
# -------------

np.genfromtxt('data/missing.dat', delimiter =",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

### What is the equivalent of enumerate for numpy arrays

In [66]:
Z = np.arange(9).reshape((3,3))
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### Generate a generic 2D Gaussian - like arrray

In [69]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X + Y * Y)
sigma, mu = 1., 0.
G = np.exp(-((D-mu)**2/(2 * sigma**2)))
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


### How to randomly palce p elements in a 2D array

In [73]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(
    Z, 
    np.random.choice(range(n*n), p, replace=False), 1
)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Substract the mean of each row of a matrix

In [74]:
X = np.random.rand(5,10)


In [75]:
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 1.44362977e-01, -4.88504658e-01,  1.66129499e-01,
         1.80594740e-01, -4.13321081e-01,  5.28916398e-02,
        -2.02855641e-01,  4.67524557e-02,  1.14756602e-01,
         3.99193466e-01],
       [-4.01832506e-01,  1.54039596e-01,  3.80911843e-01,
         1.73544688e-01,  2.50143960e-01,  2.36893957e-01,
         1.81212109e-01, -4.47514399e-01, -3.36386565e-01,
        -1.91012684e-01],
       [-5.41432077e-02, -2.98543191e-01,  2.55842253e-01,
        -2.86474825e-01,  7.25378896e-02,  4.09017906e-01,
        -2.48332704e-04, -3.76672953e-01,  3.21724892e-01,
        -4.30404316e-02],
       [-9.67083247e-02,  6.96701763e-02,  4.60138785e-02,
         2.20439568e-01, -4.48901621e-01,  1.67258684e-01,
        -2.94248740e-01,  4.39928130e-01,  7.31464875e-02,
        -1.76598239e-01],
       [-2.66762976e-02, -5.00347409e-01, -1.36768897e-01,
         4.84358003e-01, -4.25625175e-01,  4.32511978e-01,
         1.93942270e-01,  3.17448901e-01, -2.19255914e-01,
        -1.

In [76]:
X.mean(axis=1, keepdims=True)

array([[0.54245549],
       [0.61427918],
       [0.42426142],
       [0.49263049],
       [0.50969313]])

In [82]:
X[:, 0] - X.mean(axis=1)

array([ 0.14436298, -0.40183251, -0.05414321, -0.09670832, -0.0266763 ])

## numpy 51-60

### How to I sort an aray by the nth column

In [84]:
Z = np.random.randint(0, 10, (3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 8 5]
 [6 7 8]
 [7 8 7]]
[[6 7 8]
 [1 8 5]
 [7 8 7]]


### How to tel if a given 2D array has null columns

チルダは論理値の逆転

In [86]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


True


In [89]:
Z.any(axis=0)

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

### Find the nearest value from a given value in an array

flatは、flotのイテレータを作成する関数だけど、なぜ使われているのかはよくわからない. 

In [96]:
Z = np.random.uniform(0, 1, 10)
z = .5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)
k = Z[np.abs(Z-z).argmin()]
print(k)

0.48726295311899703
0.48726295311899703


In [95]:
for item in Z.flat:
    print(item)

0.02730722387634643
0.26136853561570794
0.359313318295739
0.5591935184729384
0.9774475449763771
0.5186682583824801
0.12566978954278496
0.6265854998922763
0.7063875325661331
0.4038184857073954


### Create an array class that has a name attribute

In [104]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.array(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return 
        self.info = getattr(obj, "name", "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


### Consider a given vector, how to add 1 to each element indexed by a second vector

In [105]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 5. 3. 3. 2. 3. 1. 4. 3.]


In [107]:
# 整数を集計, 上の例におけるminlengthは集計範囲の長さを決めている
np.bincount(I)

array([2, 2, 4, 2, 2, 1, 2, 0, 3, 2], dtype=int64)

### How to accumulate elements of a vector(x) to an array based on an index list

`I`を数えるときに、1をカウントするのではなく、`X`の値をカウントしていく。下の例の場合、1はＩに二個あるため、重みなしの場合には2であるが、重みがそれぜれ1と6となっていることで結果は7となる. 


In [5]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

In [4]:
np.bincount?

### Considering a (w, h, 3) image of (dtype = ubyte) , compute the number of unique colors

この場合の3点リーダーは他の次元の省略という意味のようだ. つまり`I[...,0]`は`I[:,:,0]`と等しい. 


In [7]:
w, h = 16, 16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))


[0 1]


In [15]:
np.equal(I[:,:,0],I[...,0]).all()

True

### Considering a four dimensions array, how to get sum over the last two axis at once

reshapeのときに、-1をしておくことで自動でスケールが調整されるのかな?

In [16]:
A = np.random.randint(0,10,(3,4,3,4))

In [18]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=1)
print(sum)

[[19 11 24 20 13 21 26 15 20 17 22 17]
 [25 25 25 19 25 18 24  4 12 19 14 13]
 [18 17 12 23 33 12 19 19 10 17 18 14]]


In [19]:
A.shape[:-2] + (-1,)

(3, 4, -1)

In [21]:
A.reshape(A.shape[:-2] + (-1,))

array([[[3, 0, 9, 7, 2, 5, 6, 4, 6, 8, 7, 2],
        [5, 1, 2, 2, 0, 3, 7, 4, 5, 1, 5, 0],
        [5, 2, 8, 8, 4, 4, 6, 5, 9, 2, 4, 7],
        [6, 8, 5, 3, 7, 9, 7, 2, 0, 6, 6, 8]],

       [[9, 6, 6, 6, 9, 4, 8, 0, 1, 5, 6, 3],
        [3, 8, 6, 0, 8, 4, 3, 0, 6, 3, 3, 4],
        [4, 8, 5, 5, 8, 7, 7, 1, 3, 8, 4, 4],
        [9, 3, 8, 8, 0, 3, 6, 3, 2, 3, 1, 2]],

       [[7, 7, 1, 8, 8, 2, 4, 9, 1, 4, 2, 1],
        [5, 1, 5, 4, 8, 2, 8, 8, 6, 7, 2, 7],
        [0, 3, 3, 8, 8, 0, 3, 2, 3, 0, 7, 5],
        [6, 6, 3, 3, 9, 8, 4, 0, 0, 6, 7, 1]]])

In [24]:
A.reshape(A.shape[:-2] + (-1,)).shape

(3, 4, 12)

### Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices

In [26]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights = D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.63598451 0.57992766 0.61006721 0.57341641 0.57987958 0.47362454
 0.55970618 0.49545858 0.55068354 0.21141197]


### How to get the diagonal of a dot product

In [29]:
A = np.random.randn(3,3)
B = np.random.randn(3,3)

# Slow version
np.diag(np.dot(A,B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([3.32521836, 0.94607948, 0.9878561 ])

## numpy 61-70

### Consider the vector[1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each value

In [30]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1) * (nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### Consider an array of dimension(5,5,3) , how to multiply it by an array with dimensions(5,5)

In [31]:
A = np.ones((5,5,3))
B = 2 * np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### How to swap two row of an array

In [35]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Consider a set of 10 triplets describing 10 triangles , find the set of unique line segments composing all the triangles

In [40]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype =[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)

In [41]:
print(G)

[( 5, 67) ( 5, 78) ( 8, 25) ( 8, 99) (10, 46) (10, 74) (10, 92) (10, 93)
 (19, 39) (19, 47) (24, 33) (24, 92) (25, 99) (30, 64) (30, 79) (33, 92)
 (39, 47) (46, 74) (52, 58) (52, 76) (58, 76) (59, 61) (59, 75) (61, 75)
 (62, 68) (62, 74) (64, 79) (67, 78) (68, 74) (92, 93)]


### Given anarray C that is a bincount, how to produce an array A such that np.bincount(A) == C

repeatはくり返す回数を要素ごとに指定できるようだ. 


In [42]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### How to compute averages using a sliding window over an array?

In [44]:
def moving_average(a, n = 3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

Z = np.arange(20)
print(moving_average(Z, n = 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0], Z[1], Z[2]) and each subsequent row is shifted by 1

In [48]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape = shape, strides = strides)

Z = rolling(np.arange(10), 3)
print(Z)



[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### How to negate a boolean , or to change the sign of a float inplace

In [49]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out = Z)

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1])

In [50]:
Z = np.random.uniform(-1., 1., 100)
np.negative(Z, out = Z)

array([-0.78155198,  0.41051072, -0.98197679, -0.93739744, -0.00370608,
       -0.20079289, -0.91062309,  0.69740032, -0.38821455, -0.83702687,
        0.79814645, -0.5698647 ,  0.78734683,  0.89229681, -0.71189995,
       -0.35389624,  0.48475777, -0.23209798,  0.15695221,  0.41835264,
        0.48751075, -0.54111497,  0.6588702 , -0.66115786,  0.6472596 ,
       -0.78112404,  0.06150468, -0.32022163,  0.46827587, -0.42450167,
       -0.66951114,  0.76615638, -0.69339313, -0.45805088, -0.13505305,
        0.69238411,  0.60317825, -0.78072588,  0.49461329,  0.89382091,
        0.01316698, -0.50536909,  0.71217396, -0.20933455, -0.03030879,
        0.01517669,  0.92740014, -0.1273794 , -0.59323098, -0.66597962,
       -0.70380484, -0.60119103, -0.91073481,  0.60388805, -0.49698039,
        0.88616711, -0.96536453,  0.6410341 ,  0.21148035, -0.45748386,
       -0.44042203, -0.8762779 ,  0.09473708, -0.70189165, -0.73303134,
        0.37522569,  0.33281453,  0.7519042 , -0.36672497, -0.01

### Consider 2 sets of points P0, P1 describign lines(2d) and a point p, how to compute distance from p to each line i

In [53]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis = 1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + 
         (P0[:,1] - p[..., 1]) * T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T -p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.59869798 2.78759425 5.35344606 2.83947895 2.71741369 4.11348594
 3.24314823 4.96959476 2.65998303 0.26036204]


### Consider 2 sets of points P0, P1 describling lines and a set of points P, how to compute distance from each point j to each line i

In [54]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print (np.array([distance(P0, P1, p_i) for p_i in p]))

[[ 1.98938286 12.64525194  4.1226644  12.09621515  5.87996785  0.50450866
  17.68728143  5.42211894 14.00034463  3.99649871]
 [ 6.398511    4.47350762  5.44128893  1.19282875 10.42885737  1.25245425
  10.93445928  8.99663751  4.76518367  0.393912  ]
 [ 4.44758338  5.6178427   2.63911823 10.54165872  0.55721255  7.0373375
  10.20120454  0.40775036  7.56270644  9.81270229]
 [ 3.87396061  3.06222432  1.71860525  0.56432232  4.82751199  9.27032919
   2.92623122  2.84768386  2.15545303  6.52809075]
 [ 5.57061697  7.30830436  2.41214812 12.30212663  0.20069117  6.29216251
  11.70440126  0.58364499  9.37794301  9.99374048]
 [ 0.25830618 10.96503828  4.39903145  9.84914921  6.82140686  0.14725827
  16.29993051  6.1629954  12.10048057  3.24984413]
 [ 1.93254709  1.3510474   3.47287668  6.35660334  1.15197391  9.11745229
   6.35160301  0.2579684   3.03067538  9.65028377]
 [ 5.53349541  8.54551297  1.54471595 12.89580677  0.76000257  5.21110704
  12.95367786  0.07847953 10.57285871  9.33445028]
 