# 100 numpy exerices
## numpy 1-10
### Imort the numpy package under the name

In [1]:
import numpy as np

### Print the numbpy version and the configuration

In [2]:
print (np.__version__)

1.14.0


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/P

### Create a null vector of size 10

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### How to get the documentation of the numpy add function from the command line?

関数のインフォメーションを得る方法 .


In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### Create a  null vector  of  size 10 but the fifth value which is 1

In [8]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [9]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector

In [10]:
z = np.arange(10)
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Create a 3x3 matrix with values rangin from 0 to 8

In [13]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of  non-zero elements from ....

非ゼロの要素位置を取得する. 


In [14]:
nz = np.nonzero([1,2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### Create a 3x3 idenitty matrix

In [15]:
Z = np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## numpy 11-20

### Create a  3x3x3 array with random values

In [18]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.91122417 0.56828947 0.23633536]
  [0.10220123 0.28599255 0.54029441]
  [0.02286248 0.93490127 0.16171255]]

 [[0.67595612 0.3147668  0.11979286]
  [0.25812327 0.19486783 0.03558846]
  [0.29129678 0.20383647 0.54605535]]

 [[0.01942731 0.33180026 0.053851  ]
  [0.21845907 0.1566309  0.4072349 ]
  [0.02052922 0.03294294 0.6911378 ]]]


### Create 10x10 array with uniform random values and find the minimum and maximum values

In [19]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00015150843942624004 0.9956928470144872


### Create a random vector of size 30 and find the mean

In [20]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.40525162533001396


### Create a  2d array with 1 on the border and 0 inside


In [22]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### What is the result of the following expression

Rだと`nan`の演算はすべて`nan`であるけど、Pythonでは違うようだ. 
不等式の演算はTrue/Falseが帰り値になっている. 



In [24]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
.3 == 3 * .1)

nan False False nan False


### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

引数のkは対角行列とする部分をずらすイメージでいればよい. 
k > 0 でカラム方向にずれていく. 時空間データでは必要になる場面が生じると考えられる。



In [2]:
Z = np.diag(1 + np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [3]:
np.diag(1 + np.arange(4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [4]:
np.diag(1 + np.arange(4), k = 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [6]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

### Create a 8x8 matrix and fill it with a checkerboard pattern 

しましまを作る. 

In [8]:
Z = np.zeros((8,8), dtype = int)
Z[1::2,::2] = 1 #基数行のしましま
Z[::2,1::2] = 1 #偶数行のしましま
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Consider a (6,7,8) shape array, what is the index(x,y,z) of the 100th element?

In [10]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [13]:
print(np.unravel_index(3, (2,2)))

(1, 1)


### Create a checkeboard 8x8 matrix using the tile function

これはときどき便利になるのでは・・・！？


In [15]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5x5 random matrix

In [17]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[0.92195759 0.90902994 0.59094475 0.12961208 0.9172407 ]
 [0.10333932 1.         0.08201881 0.29765987 0.53398901]
 [0.67572976 0.00371644 0.71072218 0.27422933 0.73951862]
 [0.13472703 0.28415139 0.         0.55883039 0.10891194]
 [0.82819286 0.75149406 0.16878198 0.60756313 0.57784852]]


## numpy 21-30

### Create a custom dtype that describes a color as four unisgned bytes

In [19]:
color = np.dtype([
    ("r", np.ubyte, 1), 
    ("g", np.ubyte, 1), 
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### Multiply a 5x3 matrix by a 3x2 matrix

In [21]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### Given a 1D array, negate all elements which are between 3 and 8, in place

In [23]:
# Author: Evgeni Burovki
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### What is the output of the following script ?

これは恐い。。。pythonにライブラリーを読み込むときには、必ずmoduleとして読み込むということを意識したい。。。

In [25]:
# Author: Jake VanderPlas

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


### Consider an integer vector Z,, which of these expressions are legal?

In [43]:
Z = np.arange(5, dtype = np.int)
print(
    Z ** Z, 
    2 << Z, # 2をZビット左にずらす  001 -> 100, 
    Z >> 2, # Zを2ビット右にずらす　100 -> 001
    2 << Z >> 2, 
    1j * Z, 
    Z / 1/ 1, 
    # Z < Z > Z
)

[  1   1   4  27 256] [ 2  4  8 16 32] [0 0 0 0 1] [0 1 2 4 8] [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j] [0. 1. 2. 3. 4.]


### What are the result of the following expressions?

In [46]:
print(
    np.array(0), 
    np.array(0) // np.array(0), 
    np.array(0) // np.array(.0),
    np.array(0) / np.array(0.),
    np.array(0) / np.array(0)
)

0 0 nan nan nan


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in floor_divide
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


### How to round away from zero a float array


In [49]:
# Author: Charles R Harris

Z = np.random.uniform(-10, 10, 10)
print(
    np.trunc(Z + np.copysign(.5, Z))
)

[-2. -1. -7.  4. -7.  4. -7. -5.  9. -0.]


In [55]:
# 0.5に、Zの符号をコピーさせる
np.copysign(.5, Z)

array([-0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5])

In [56]:
Z

array([-1.65708739, -1.48084382, -7.04114379,  3.86602668, -6.94377156,
        4.496215  , -6.80105232, -5.28647511,  8.97518993, -0.28001812])

### Extract the integer part of a random arrary using 5 diffrent methods

In [60]:
Z = np.random.uniform(-10, 10, 10)

print (Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 6.74706849 -9.26265319  8.20958221 -4.46451684 -4.45367709  3.73600485
 -4.81089396 -2.79760124 -7.87712466  0.29938869]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[  6. -10.   8.  -5.  -5.   3.  -5.  -3.  -8.   0.]
[ 6 -9  8 -4 -4  3 -4 -2 -7  0]
[ 6. -9.  8. -4. -4.  3. -4. -2. -7.  0.]


In [61]:
Z%1

array([0.74706849, 0.73734681, 0.20958221, 0.53548316, 0.54632291,
       0.73600485, 0.18910604, 0.20239876, 0.12287534, 0.29938869])

### Create a 5x5 matrix with row values ranging from 0 to 4

In [63]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Consider a generator function that generates 10 integers and use it to build an array

In [66]:
def generate():
    for x in arange(10):
        yield x

Z = np.fromiter(generate(), dtype = float, count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
